### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by matentzn** [balhoff/owl-diff#2]
@balhoff Awesome tool Jim, thanks for that :P 

Any idea why I get an internal server error when I call this:

https://stars-app.renci.org/owldiff/diff?left=https://raw.githubusercontent.com/FlyBase/drosophila-developmental-ontology/master/src/ontology/fbdv-edit.obo&right=https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbdv/src/trunk/ontologies/fbdv-edit.obo&loadimports=true

**Comment by balhoff** [comment]
```
Future(Failure(org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/fbdv/imports/go_import.owl> Cause: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbdv/releases/imports/go_import.owl))
```

**Comment by matentzn** [comment]
Ok got it. Thanks. Master was not commited yet!
