### ISSUE TITLE
Diff Renderer does not write import changes

### ISSUE THREAD

**Issue by beckyjackson** [balhoff/owl-diff#4]
When diffing two identical ontologies using ROBOT, with the only difference being:
```
<owl:imports rdf:resource="https://github.com/ontodev/robot/examples/edit.owl"/>
```
Vs.
```
<owl:imports rdf:resource="https://github.com/ontodev/robot/examples/foo.owl"/>
```

The result is:
```
0 axioms in Ontology 1 but not in Ontology 2:

0 axioms in Ontology 2 but not in Ontology 1:

```

The differ registers that something is different (otherwise it would write `Ontologies are identical`), but it does not include the import statement.

**Comment by balhoff** [comment]
@beckyjackson if you use the HTML or Markdown output, you will see the import change. I believe the plain text output works the way it does for compatibility with the previous ROBOT behavior. But I can see how this is confusing and I am fine with changing the plain text output to include the imports change. Is there any reason to worry about being different from old ROBOT output in this one case?

**Comment by beckyjackson** [comment]
Hmm - let's wait for @jamesaoverton to get back. Thanks for following up so quickly!

**Comment by jamesaoverton** [comment]
Let's change the plain text output to include import changes. I consider that a bug fix.

**Comment by balhoff** [comment]
@beckyjackson watch for v1.1.2 to appear on Maven Central. I released it but it's not on the site yet.

**Comment by beckyjackson** [comment]
Great, thank you!
