### ISSUE TITLE
Owlapi version 4.5.22 upgrade problem

### ISSUE THREAD

**Issue by hkir-dev** [balhoff/owl-diff#42]
We are upgrading [ROBOT](https://github.com/ontodev/robot) to owlapi 4.5.22. We observed some behavior changes (mostly related with handling owl reification axioms) in the owl-diff with the new owlapi jar.

Can we make a new release of owl-diff with owlapi 4.5.22?

Left ontology: https://github.com/ontodev/robot/blob/master/docs/examples/edit.owl
Right ontology: https://github.com/ontodev/robot/blob/master/docs/examples/release.owl
Old diff (owlapi 4.5.6): https://github.com/ontodev/robot/blob/master/docs/examples/release-diff.txt
New diff (owlapi 4.5.22):  [release-diff.txt](https://github.com/balhoff/owl-diff/files/8728344/release-diff.txt)

**Comment by matentzn** [comment]
Is this necessary for the robot pr? You can't just exclude the old OWLAPI in the Pom, and it works?

**Comment by matentzn** [comment]
Wait the second diff, is it between an ontology serialised by the old owl api compared to one serialised by the new? Why is the diff so huge?

**Comment by hkir-dev** [comment]
Yes, issue is not jar conflict, we are already excluding. 
Second diff is generated using the new owlapi. Seems the way owlapi handle OWL reification (and RDF also) changed.

**Comment by matentzn** [comment]
Changed how?

**Comment by hkir-dev** [comment]
Not really sure, I lokked for it but couldn't find much detail. Just commenting based on the output. 
But in another case I also observed that Owlapi isn't providing RDF reification axioms as unparsed triples any more.

**Comment by hkir-dev** [comment]
> Wait the second diff, is it between an ontology serialised by the old owl api compared to one serialised by the new? Why is the diff so huge?

By the way I am not serializing the input ontologies in different versions. Just processing the same ontologies using different owlapi versions:
```
robot diff --left edit.owl \
  --right release.owl \
  --output results/release-diff.txt
```

**Comment by matentzn** [comment]
Worrying

**Comment by balhoff** [comment]
If you parse the ontology https://github.com/ontodev/robot/raw/master/docs/examples/edit.owl using OWL API 4.5.6, it says it has 703 logical axioms. If you parse it with 4.5.22 it says it has 705 logical axioms. I kind of doubt this is an issue with owl-diff. It just compares sets of axioms provided by OWL API.

**Comment by balhoff** [comment]
The input ontology seems to use a lot of undeclared annotation properties. It looks like axiom annotations using these properties are not getting parsed in 4.5.22:

```
- AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#date_retrieved> "2012-06-20"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#external_class> "AAO:0010279"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#ontology> "AAO"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#source> "AAO:BJB"^^xsd:string) <http://purl.obolibrary.org/obo/UBPROP_0000001> <http://purl.obolibrary.org/obo/UBERON_0000949> "Anatomical system containing glands which regulates bodily functions though the secretion of hormones.[AAO]"^^xsd:string)
+ AnnotationAssertion(<http://purl.obolibrary.org/obo/UBPROP_0000001> <http://purl.obolibrary.org/obo/UBERON_0000949> "Anatomical system containing glands which regulates bodily functions though the secretion of hormones.[AAO]"^^xsd:string)
```

**Comment by matentzn** [comment]
Yeah its definitely an OWLAPI issue, not an owl-diff issue, that's for sure.. Wow, ok. undeclared APs lead to axiom annos being ignored. Big thing.

**Comment by matentzn** [comment]
How do we feel about this Jim? Kinda sounds right but maybe churny..

**Comment by hkir-dev** [comment]
> The input ontology seems to use a lot of undeclared annotation properties. It looks like axiom annotations using these properties are not getting parsed in 4.5.22:

Isn't it the inverse? In my case axiom annotations using those properties are not getting parsed in 4.5.6, but they are parsed in 4.5.22. 
So 4.5.22 has better and lossless parsing but significantly effecting our backward compatibility.

**Comment by balhoff** [comment]
@hkir-dev the unparsed triples reporting might be misleading here. There were some recent OWL API fixes related to that (the unparsed messages were incorrect). I am confused now though, because the properties are declared in the "right" ontology, and that's where they seem not to be parsed. Is that right? I will need to look more carefully.
