### ISSUE TITLE
canonically sort diff results

### ISSUE THREAD

**Issue by jclerman** [balhoff/owl-diff#82]
Currently, the individual elements of rendered diffs do not seem to be sorted.  That has impacts for `robot` (see https://github.com/ontodev/robot/issues/1192), whose diff-results have some inconsistency (not in semantic meaning of course, but in terms of literal reproducibility).

Readability of results is also somewhat impaired, since, for example, for a class, differences in subclass axioms may appear mixed in with annotation differences, rather than in a consistent location (top of the list, say).

The code that attempts to sort results appears to be [here](https://github.com/balhoff/owl-diff/blob/master/src/main/scala/org/geneontology/owl/differ/render/MarkdownGroupedDiffRenderer.scala#L41-L43).  Not sure that it's working as intended though. 

 I also note that this library doesn't have a test-suite - adding one would facilitate contributions (and have the usual benefits, of course).

**Comment by balhoff** [comment]
I agree the output should be consistent. Also agree about tests. I will try to get to these changes soon, but right now not sure when that will be.
